from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendario = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendario.setGeometry(QtCore.QRect(10, 10, 400, 250))
        self.calendario.setGridVisible(False)
        self.calendario.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.SingleLetterDayNames)
        self.calendario.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendario.setNavigationBarVisible(True)
        self.calendario.setDateEditEnabled(True)
        self.calendario.setObjectName("calendario")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 10, 401, 281))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 30))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 60, 30))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 60, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 60, 30))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.text_fecha = QtWidgets.QLineEdit(self.frame)
        self.text_fecha.setGeometry(QtCore.QRect(90, 20, 113, 30))
        self.text_fecha.setObjectName("text_fecha")
        self.text_hora = QtWidgets.QLineEdit(self.frame)
        self.text_hora.setGeometry(QtCore.QRect(90, 60, 113, 30))
        self.text_hora.setObjectName("text_hora")
        self.text_asunto = QtWidgets.QLineEdit(self.frame)
        self.text_asunto.setGeometry(QtCore.QRect(90, 100, 113, 30))
        self.text_asunto.setObjectName("text_asunto")
        self.text_nota = QtWidgets.QTextEdit(self.frame)
        self.text_nota.setGeometry(QtCore.QRect(90, 140, 291, 111))
        self.text_nota.setObjectName("text_nota")
        self.lista = QtWidgets.QListWidget(self.centralwidget)
        self.lista.setGeometry(QtCore.QRect(10, 280, 400, 211))
        self.lista.setObjectName("lista")
        item = QtWidgets.QListWidgetItem()
        self.lista.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lista.addItem(item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Fecha:"))
        self.label_2.setText(_translate("MainWindow", "Hora:"))
        self.label_3.setText(_translate("MainWindow", "Asunto:"))
        self.label_4.setText(_translate("MainWindow", "Nota:"))
        __sortingEnabled = self.lista.isSortingEnabled()
        self.lista.setSortingEnabled(False)
        item = self.lista.item(0)
        item.setText(_translate("MainWindow", "elemento 1"))
        item = self.lista.item(1)
        item.setText(_translate("MainWindow", "elemento 2"))
        self.lista.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
